local:
  server:
    short-port: 8888
    long-port: 8889

spring:
  redis:
    jedis:
      pool:
        max-wait-millis: 1000
        max-total: 500
        max-idle: 20
        redis_test_on_borrow: true
    cluster:
      nodes: 10.90.18.3:6379,10.90.18.4:6379,10.90.18.5:6379,10.90.18.6:6379,10.90.18.7:6379,10.80.5.148:6379,10.80.8.148:6379,10.90.114.25:6379
      connection-timeout: 200
      socket-timeout: 200
      max-redirects: 3
      pwd: md34fjmhsJHhgmnjka678i
    cloud-cluster:
      host: 10.61.223.6
      port: 81
      pwd: md34fjmhsJHhgmnjka678i
      connection-timeout: 1000
      pool:
        max-wait-millis: 5000
        max-total: 500
        max-idle: 20
        redis_test_on_borrow: true
    single:
      host: 10.61.16.5
      port: 6379
      pwd: dmd3#fjmh2sJHhgmnjka678i
      connection-timeout: 1000
      pool:
        max-wait-millis: 5000
        max-total: 80
        max-idle: 20
        redis_test_on_borrow: true
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mysharkdb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      readOnly: false
      connectionTimeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idleTimeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      maxLifetime: 600000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximumPoolSize: 15 #连接池中允许的最大连接数
  mail:
    username: ad-tech-ext
    password: Ggxt20220315
    host: mail.staff.ifeng.com
    from: ad-tech-ext@ifeng.com
    to: baibq@ifeng.com;wang_huihui@ifeng.com;yuanyj1@ifeng.com;zhaodan@ifeng.com;lichong1@ifeng.com;guobj@ifeng.com;wangsh5@ifeng.com;yaoya@ifeng.com;jiangja@ifeng.com
    warntime: 2 #连续几次惩罚发报警邮件

vertx:
  verticle:
    instance: 10
    work-pool-size: 100
  http:
    client:
      pool-size: 100
      idle-timeout: 500
      queue-size: 1000

kafka:
  servers: alikafka-post-cn-2r42yyuab002-1-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-2r42yyuab002-2-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-2r42yyuab002-3-vpc.alikafka.aliyuncs.com:9092
  readtopic: ifs_service_test
  writetopic: muta_mssage_bus_test
  sdkwritetopic: muta_config_message_bus_test
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  group-id: mutacenter
  auto-offset-reset: latest
  enable-auto-commit: true
  acks: 1

mutacenter:
  corePoolSize: 10 #线程池维护线程的最少核心数量
  maximumPoolSize: 30 #线程池维护线程的最大数量
  keepAliveTime: 5000 #线程池维护线程所允许的空闲时间(单位毫秒)
  blockingQueueSize: 100 #缓存队列长度

debugsql: false
debugredis: false